-- Elector — rewarded ads for Campaign Funds.
--
-- Apply after profiles.sql. The client never chooses the payout amount; this RPC
-- rolls 20-60 Funds on the server and enforces 5 rewarded ads per 12 hours.

create table if not exists public.ad_rewards (
  id         bigint      generated by default as identity primary key,
  user_id    uuid        not null references auth.users(id) on delete cascade,
  amount     integer     not null check (amount between 20 and 60),
  placement  text        not null default 'shop',
  provider   text,
  ad_unit    text,
  created_at timestamptz not null default now()
);

create index if not exists ad_rewards_user_created_idx
  on public.ad_rewards (user_id, created_at desc);

alter table public.ad_rewards enable row level security;

drop policy if exists ad_rewards_select_own on public.ad_rewards;
create policy ad_rewards_select_own on public.ad_rewards
  for select using (auth.uid() = user_id);

create or replace function public.get_ad_reward_status()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid           uuid := auth.uid();
  c_limit         constant integer := 5;
  c_window        constant interval := interval '12 hours';
  v_watched       integer;
  v_oldest_recent timestamptz;
begin
  if v_uid is null then raise exception 'auth required'; end if;

  select count(*), min(created_at)
    into v_watched, v_oldest_recent
    from public.ad_rewards
    where user_id = v_uid
      and created_at > now() - c_window;

  return jsonb_build_object(
    'watched', coalesce(v_watched, 0),
    'remaining', greatest(0, c_limit - coalesce(v_watched, 0)),
    'limit', c_limit,
    'windowHours', 12,
    'nextResetAt',
      case when coalesce(v_watched, 0) >= c_limit
        then v_oldest_recent + c_window
        else null
      end
  );
end; $$;

create or replace function public.claim_ad_reward(
  p_placement text default 'shop',
  p_provider  text default null,
  p_ad_unit   text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid           uuid := auth.uid();
  prof            public.profiles;
  c_limit         constant integer := 5;
  c_window        constant interval := interval '12 hours';
  v_watched       integer;
  v_oldest_recent timestamptz;
  v_amount        integer;
  v_balance       integer;
  v_remaining     integer;
begin
  if v_uid is null then raise exception 'auth required'; end if;

  -- Lock the profile row so concurrent claim attempts serialize per account.
  select * into prof from public.profiles where id = v_uid for update;
  if prof.id is null then raise exception 'claim_ad_reward: no profile'; end if;

  select count(*), min(created_at)
    into v_watched, v_oldest_recent
    from public.ad_rewards
    where user_id = v_uid
      and created_at > now() - c_window;

  if coalesce(v_watched, 0) >= c_limit then
    return jsonb_build_object(
      'status', 'limit',
      'amount', 0,
      'balance', prof.campaign_funds,
      'watched', coalesce(v_watched, 0),
      'remaining', 0,
      'limit', c_limit,
      'windowHours', 12,
      'nextResetAt', v_oldest_recent + c_window
    );
  end if;

  v_amount := 20 + floor(random() * 41)::integer;

  insert into public.ad_rewards (user_id, amount, placement, provider, ad_unit)
  values (
    v_uid,
    v_amount,
    left(coalesce(nullif(btrim(p_placement), ''), 'shop'), 64),
    left(nullif(btrim(coalesce(p_provider, '')), ''), 64),
    left(nullif(btrim(coalesce(p_ad_unit, '')), ''), 120)
  );

  update public.profiles
    set campaign_funds = campaign_funds + v_amount,
        updated_at = now()
    where id = v_uid
    returning campaign_funds into v_balance;

  v_remaining := greatest(0, c_limit - (coalesce(v_watched, 0) + 1));

  return jsonb_build_object(
    'status', 'claimed',
    'amount', v_amount,
    'balance', v_balance,
    'watched', coalesce(v_watched, 0) + 1,
    'remaining', v_remaining,
    'limit', c_limit,
    'windowHours', 12,
    'nextResetAt',
      case when v_remaining = 0
        then coalesce(v_oldest_recent, now()) + c_window
        else null
      end
  );
end; $$;

revoke execute on function public.get_ad_reward_status() from public, anon;
grant execute on function public.get_ad_reward_status() to authenticated;

revoke execute on function public.claim_ad_reward(text, text, text) from public, anon;
grant execute on function public.claim_ad_reward(text, text, text) to authenticated;
