// ════════════════════════════════════════════════════════════════════════════
// resolve-turn — server-authoritative multiplayer turn resolution
//
// Deploy:  npm run build:edge && supabase functions deploy resolve-turn
//
// WHY: previously the "host" browser ran resolveTurn() locally and pushed the
// result, so a malicious host could doctor their own lobby's resolved state.
// This function runs the SAME engine server-side with the service-role key and
// is the only writer of resolved turns. Clients just invoke it.
//
// SECURITY:
//   • Caller is identified from their JWT (anon or email user) and must be a
//     participant of the lobby (checked against lobby_participants).
//   • The authoritative read/write uses the service-role key (bypasses RLS).
//   • `force` is only honored if the turn deadline has genuinely passed
//     (server clock), so it can't be abused to resolve early.
//   • A compare-and-set on phase='PLANNING' prevents double-resolution when
//     Realtime delivers the all-submitted event more than once.
//
// The _engine/ directory is generated by scripts/build-edge-function.mjs.
// ════════════════════════════════════════════════════════════════════════════
import { createClient } from 'jsr:@supabase/supabase-js@2';
import { resolveLobbyTurn } from './_engine/resolveLobbyTurn.ts';
import type { LobbyGameState } from './_engine/types.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) return json({ error: 'missing auth' }, 401);

    const url = Deno.env.get('SUPABASE_URL')!;
    const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const anonKey = Deno.env.get('SUPABASE_ANON_KEY')!;

    // Identify the caller from their JWT (works for anonymous sign-ins too).
    const userClient = createClient(url, anonKey, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: userData, error: userErr } = await userClient.auth.getUser();
    if (userErr || !userData.user) return json({ error: 'invalid auth' }, 401);
    const uid = userData.user.id;

    const { lobbyId, force } = (await req.json().catch(() => ({}))) as {
      lobbyId?: string;
      force?: boolean;
    };
    if (!lobbyId) return json({ error: 'lobbyId required' }, 400);

    // Privileged client for the authoritative read/write (bypasses RLS).
    const admin = createClient(url, serviceKey);

    // The caller must be a participant of this lobby.
    const { data: member } = await admin
      .from('lobby_participants')
      .select('player_id')
      .eq('lobby_id', lobbyId)
      .eq('auth_uid', uid)
      .maybeSingle();
    if (!member) return json({ error: 'not a participant' }, 403);

    const { data: row, error: rowErr } = await admin
      .from('lobbies')
      .select('game_state, status')
      .eq('id', lobbyId)
      .single();
    if (rowErr || !row?.game_state) return json({ error: 'lobby not found' }, 404);

    const remote = row.game_state as LobbyGameState;
    if (remote.phase !== 'PLANNING') return json({ skipped: 'not planning' });

    // Force is only valid once the (server-evaluated) turn deadline has passed.
    const deadlinePassed = !!remote.turnDeadlineUtc && Date.now() >= remote.turnDeadlineUtc;
    const outcome = resolveLobbyTurn(remote, force === true && deadlinePassed);
    if (!outcome) return json({ skipped: 'not all submitted' });

    // Compare-and-set: only write if the row is STILL in PLANNING. A concurrent
    // duplicate invocation will match zero rows and no-op.
    const { data: updated, error: updErr } = await admin
      .from('lobbies')
      .update({ game_state: outcome.resolved, updated_at: new Date().toISOString() })
      .eq('id', lobbyId)
      .filter('game_state->>phase', 'eq', 'PLANNING')
      .select('id');
    if (updErr) return json({ error: updErr.message }, 500);
    if (!updated || updated.length === 0) return json({ skipped: 'already resolved' });

    return json({ resolved: outcome.resolved });
  } catch (e) {
    return json({ error: String(e) }, 500);
  }
});
