// ════════════════════════════════════════════════════════════════════════════
// resolve-turn — server-authoritative multiplayer turn resolution
//
// Deploy:  npm run build:edge && supabase functions deploy resolve-turn
//
// WHY: previously the "host" browser ran resolveTurn() locally and pushed the
// result, so a malicious host could doctor their own lobby's resolved state.
// This function runs the SAME engine server-side with the service-role key and
// is the only writer of resolved turns. Clients just invoke it.
//
// SECURITY:
//   • Caller is identified from their JWT (anon or email user) and must be a
//     participant of the lobby (checked against lobby_participants).
//   • The authoritative read/write uses the service-role key (bypasses RLS).
//   • `force` is only honored if the turn deadline has genuinely passed
//     (server clock), so it can't be abused to resolve early.
//   • A compare-and-set on phase='PLANNING' prevents double-resolution when
//     Realtime delivers the all-submitted event more than once.
//
// The _engine/ directory is generated by scripts/build-edge-function.mjs.
// ════════════════════════════════════════════════════════════════════════════
import { createClient } from 'jsr:@supabase/supabase-js@2';
import { resolveLobbyTurn } from './_engine/resolveLobbyTurn.ts';
import { advanceLobbyPhase, REQUIRED_PHASE, type PhaseAction } from './_engine/advanceLobbyPhase.ts';
import {
  buildLobbyGameStateFromWaiting,
  buildPendingSubmission,
  normalizePurchaseIntents,
  normalizeTurnTimeLimit,
} from './_engine/lobbySecurity.ts';
import type { LobbyGameState, WaitingLobbyState } from './_engine/types.ts';
import { rollHitsChance, rollModifierIds, applyRolledModifiers, isCrazyModeAvailable } from './_engine/modifiers.ts';
import { pushToLobby } from '../_shared/apns.ts';

// Restrict cross-origin callers to our own surfaces (defense-in-depth; the JWT
// is still validated below). Tauri mobile/desktop webviews use the tauri origins.
const ALLOWED_ORIGINS = new Set<string>([
  'https://playelector.com',
  'https://www.playelector.com',
  'http://localhost:5174',
  'tauri://localhost',
  'https://tauri.localhost',
  'http://tauri.localhost',
]);
const FALLBACK_ORIGIN = 'https://playelector.com';

function corsFor(req: Request): Record<string, string> {
  const origin = req.headers.get('Origin') ?? '';
  const allow = ALLOWED_ORIGINS.has(origin) ? origin : FALLBACK_ORIGIN;
  return {
    'Access-Control-Allow-Origin': allow,
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Vary': 'Origin',
  };
}

const PHASE_ACTIONS = new Set<PhaseAction>(['confirmResolution', 'resolveElection', 'completeTally']);

function json(body: unknown, status = 200, cors: Record<string, string> = {}): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...cors, 'Content-Type': 'application/json' },
  });
}

// Run a best-effort side task (push notifications) without blocking or failing
// the response. Uses the platform's waitUntil when present so the task survives
// past the response; otherwise fires it detached. Errors are always swallowed —
// a push failure must never affect turn resolution.
function background(task: Promise<unknown>): void {
  const ert = (globalThis as { EdgeRuntime?: { waitUntil?: (p: Promise<unknown>) => void } }).EdgeRuntime;
  const safe = task.catch(() => {});
  if (ert?.waitUntil) ert.waitUntil(safe);
  else void safe;
}

Deno.serve(async (req: Request) => {
  const cors = corsFor(req);
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors });

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) return json({ error: 'missing auth' }, 401, cors);

    const url = Deno.env.get('SUPABASE_URL')!;
    const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const anonKey = Deno.env.get('SUPABASE_ANON_KEY')!;

    // Identify the caller from their JWT (works for anonymous sign-ins too).
    const userClient = createClient(url, anonKey, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: userData, error: userErr } = await userClient.auth.getUser();
    if (userErr || !userData.user) return json({ error: 'invalid auth' }, 401, cors);
    const uid = userData.user.id;

    const { lobbyId, force, action, playerId, intents, turnTimeLimitSec } =
      (await req.json().catch(() => ({}))) as {
      lobbyId?: string;
      force?: boolean;
      action?: string;
      playerId?: string;
      intents?: unknown;
      turnTimeLimitSec?: unknown;
    };
    if (!lobbyId) return json({ error: 'lobbyId required' }, 400, cors);

    // Privileged client for the authoritative read/write (bypasses RLS).
    const admin = createClient(url, serviceKey);

    // The caller must be a participant of this lobby.
    const { data: member } = await admin
      .from('lobby_participants')
      .select('player_id')
      .eq('lobby_id', lobbyId)
      .eq('auth_uid', uid)
      .maybeSingle();
    if (!member) return json({ error: 'not a participant' }, 403, cors);

    const { data: row, error: rowErr } = await admin
      .from('lobbies')
      .select('game_state, status, host_uid, crazy_mode')
      .eq('id', lobbyId)
      .single();
    if (rowErr || !row?.game_state) return json({ error: 'lobby not found' }, 404, cors);

    // ── Branch 0: host starts the waiting room with server-built state ─────────
    if (action === 'startGame') {
      if (row.host_uid !== uid) return json({ error: 'only the host may start the game' }, 403, cors);
      if (row.status !== 'waiting') return json({ error: 'lobby not waiting' }, 409, cors);

      const next = buildLobbyGameStateFromWaiting(
        row.game_state as WaitingLobbyState,
        Date.now(),
        normalizeTurnTimeLimit(turnTimeLimitSec),
      );
      if (!next) return json({ error: 'invalid waiting lobby' }, 400, cors);

      // ── Modifier roll (server-authoritative so all seats get the same twist) ──
      // Crazy Mode (opt-in, until Aug 20) guarantees 2 distinct modifiers; every
      // other online game has the standard 40% chance of one. Cutoff enforced here,
      // not just by hiding the client toggle.
      const crazy = row.crazy_mode === true && isCrazyModeAvailable(Date.now());
      const modifierIds = crazy
        ? rollModifierIds(2, [], Math.random)
        : (rollHitsChance(Math.random) ? rollModifierIds(1, [], Math.random) : []);
      applyRolledModifiers(next, modifierIds);

      const { data: updated, error: updErr } = await admin
        .from('lobbies')
        .update({ status: 'in_progress', game_state: next, updated_at: new Date().toISOString() })
        .eq('id', lobbyId)
        .eq('status', 'waiting')
        .select('id');
      if (updErr) return json({ error: updErr.message }, 500, cors);
      if (!updated || updated.length === 0) return json({ skipped: 'already started' }, 200, cors);

      // Tell the other players (not the host who just started) the match is live.
      background(pushToLobby(admin, lobbyId, {
        title: 'Your match has begun',
        body: 'The race to 270 is on — make your first move.',
        data: { lobbyId },
      }, uid));
      return json({ resolved: next }, 200, cors);
    }

    const remote = row.game_state as LobbyGameState;

    // ── Branch 0b: submit a validated turn intent as the caller's own seat ─────
    if (action === 'submitTurn') {
      const ownedPlayerId = member.player_id as string;
      if (playerId && playerId !== ownedPlayerId) return json({ error: 'cannot submit as another player' }, 403, cors);
      if (row.status !== 'in_progress' || remote.phase !== 'PLANNING') {
        return json({ error: 'lobby not accepting submissions' }, 409, cors);
      }

      const normalized = normalizePurchaseIntents(intents);
      if (!normalized) return json({ error: 'invalid purchase intents' }, 400, cors);

      const built = buildPendingSubmission(remote, ownedPlayerId, normalized);
      if (built.error) return json({ error: built.error }, 400, cors);

      const { error: submitErr } = await admin.rpc('submit_turn_pending', {
        p_lobby_id: lobbyId,
        p_player_id: ownedPlayerId,
        p_pending: built.pending,
        p_auth_uid: uid,
      });
      if (submitErr) return json({ error: submitErr.message }, 500, cors);

      return json({ ok: true }, 200, cors);
    }

    // ── Branch 1: post-resolution phase advance (server-authoritative) ─────────
    if (action && PHASE_ACTIONS.has(action as PhaseAction)) {
      const act = action as PhaseAction;
      const required = REQUIRED_PHASE[act];
      if (remote.phase !== required) return json({ skipped: 'phase mismatch' }, 200, cors);

      const next = advanceLobbyPhase(remote, act, Date.now());
      if (!next) return json({ skipped: 'no-op' }, 200, cors);

      // Compare-and-set on the expected phase so duplicate calls no-op.
      const { data: updated, error: updErr } = await admin
        .from('lobbies')
        .update({ game_state: next, updated_at: new Date().toISOString() })
        .eq('id', lobbyId)
        .filter('game_state->>phase', 'eq', required)
        .select('id');
      if (updErr) return json({ error: updErr.message }, 500, cors);
      if (!updated || updated.length === 0) return json({ skipped: 'already advanced' }, 200, cors);

      // When the game ends, also flip the lobby lifecycle to finished.
      if (next.phase === 'GAME_OVER') {
        await admin.from('lobbies').update({ status: 'finished' }).eq('id', lobbyId);
        background(pushToLobby(admin, lobbyId, {
          title: 'Final results are in',
          body: 'See how the election played out.',
          data: { lobbyId },
        }));
      } else if (next.phase === 'PLANNING') {
        // A fresh planning round — nudge the other players to take their turn.
        background(pushToLobby(admin, lobbyId, {
          title: 'Your move',
          body: 'A new round has begun — submit your campaign moves.',
          data: { lobbyId },
        }, uid));
      }
      return json({ resolved: next }, 200, cors);
    }

    // ── Branch 2: PLANNING → RESOLUTION turn resolution ────────────────────────
    if (remote.phase !== 'PLANNING') return json({ skipped: 'not planning' }, 200, cors);

    // Force is only valid once the (server-evaluated) turn deadline has passed.
    const deadlinePassed = !!remote.turnDeadlineUtc && Date.now() >= remote.turnDeadlineUtc;
    const outcome = resolveLobbyTurn(remote, force === true && deadlinePassed);
    if (!outcome) return json({ skipped: 'not all submitted' }, 200, cors);

    // Compare-and-set: only write if the row is STILL in PLANNING. A concurrent
    // duplicate invocation will match zero rows and no-op.
    const { data: updated, error: updErr } = await admin
      .from('lobbies')
      .update({ game_state: outcome.resolved, updated_at: new Date().toISOString() })
      .eq('id', lobbyId)
      .filter('game_state->>phase', 'eq', 'PLANNING')
      .select('id');
    if (updErr) return json({ error: updErr.message }, 500, cors);
    if (!updated || updated.length === 0) return json({ skipped: 'already resolved' }, 200, cors);

    return json({ resolved: outcome.resolved }, 200, cors);
  } catch (e) {
    return json({ error: String(e) }, 500, corsFor(req));
  }
});
