// ════════════════════════════════════════════════════════════════════════════
// resolve-turn — server-authoritative multiplayer turn resolution
//
// Deploy:  npm run build:edge && supabase functions deploy resolve-turn
//
// WHY: previously the "host" browser ran resolveTurn() locally and pushed the
// result, so a malicious host could doctor their own lobby's resolved state.
// This function runs the SAME engine server-side with the service-role key and
// is the only writer of resolved turns. Clients just invoke it.
//
// SECURITY:
//   • Caller is identified from their JWT (anon or email user) and must be a
//     participant of the lobby (checked against lobby_participants).
//   • The authoritative read/write uses the service-role key (bypasses RLS).
//   • `force` is only honored if the turn deadline has genuinely passed
//     (server clock), so it can't be abused to resolve early.
//   • A compare-and-set on phase='PLANNING' prevents double-resolution when
//     Realtime delivers the all-submitted event more than once.
//
// The _engine/ directory is generated by scripts/build-edge-function.mjs.
// ════════════════════════════════════════════════════════════════════════════
import { createClient } from 'jsr:@supabase/supabase-js@2';
import { resolveLobbyTurn } from './_engine/resolveLobbyTurn.ts';
import { advanceLobbyPhase, REQUIRED_PHASE, type PhaseAction } from './_engine/advanceLobbyPhase.ts';
import type { LobbyGameState } from './_engine/types.ts';

// Restrict cross-origin callers to our own surfaces (defense-in-depth; the JWT
// is still validated below). Tauri mobile/desktop webviews use the tauri origins.
const ALLOWED_ORIGINS = new Set<string>([
  'https://playelector.com',
  'https://www.playelector.com',
  'http://localhost:5174',
  'tauri://localhost',
  'https://tauri.localhost',
  'http://tauri.localhost',
]);
const FALLBACK_ORIGIN = 'https://playelector.com';

function corsFor(req: Request): Record<string, string> {
  const origin = req.headers.get('Origin') ?? '';
  const allow = ALLOWED_ORIGINS.has(origin) ? origin : FALLBACK_ORIGIN;
  return {
    'Access-Control-Allow-Origin': allow,
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Vary': 'Origin',
  };
}

const PHASE_ACTIONS = new Set<PhaseAction>(['confirmResolution', 'resolveElection', 'completeTally']);

function json(body: unknown, status = 200, cors: Record<string, string> = {}): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...cors, 'Content-Type': 'application/json' },
  });
}

Deno.serve(async (req: Request) => {
  const cors = corsFor(req);
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors });

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) return json({ error: 'missing auth' }, 401, cors);

    const url = Deno.env.get('SUPABASE_URL')!;
    const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const anonKey = Deno.env.get('SUPABASE_ANON_KEY')!;

    // Identify the caller from their JWT (works for anonymous sign-ins too).
    const userClient = createClient(url, anonKey, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: userData, error: userErr } = await userClient.auth.getUser();
    if (userErr || !userData.user) return json({ error: 'invalid auth' }, 401, cors);
    const uid = userData.user.id;

    const { lobbyId, force, action } = (await req.json().catch(() => ({}))) as {
      lobbyId?: string;
      force?: boolean;
      action?: string;
    };
    if (!lobbyId) return json({ error: 'lobbyId required' }, 400, cors);

    // Privileged client for the authoritative read/write (bypasses RLS).
    const admin = createClient(url, serviceKey);

    // The caller must be a participant of this lobby.
    const { data: member } = await admin
      .from('lobby_participants')
      .select('player_id')
      .eq('lobby_id', lobbyId)
      .eq('auth_uid', uid)
      .maybeSingle();
    if (!member) return json({ error: 'not a participant' }, 403, cors);

    const { data: row, error: rowErr } = await admin
      .from('lobbies')
      .select('game_state, status')
      .eq('id', lobbyId)
      .single();
    if (rowErr || !row?.game_state) return json({ error: 'lobby not found' }, 404, cors);

    const remote = row.game_state as LobbyGameState;

    // ── Branch 1: post-resolution phase advance (server-authoritative) ─────────
    if (action && PHASE_ACTIONS.has(action as PhaseAction)) {
      const act = action as PhaseAction;
      const required = REQUIRED_PHASE[act];
      if (remote.phase !== required) return json({ skipped: 'phase mismatch' }, 200, cors);

      const next = advanceLobbyPhase(remote, act, Date.now());
      if (!next) return json({ skipped: 'no-op' }, 200, cors);

      // Compare-and-set on the expected phase so duplicate calls no-op.
      const { data: updated, error: updErr } = await admin
        .from('lobbies')
        .update({ game_state: next, updated_at: new Date().toISOString() })
        .eq('id', lobbyId)
        .filter('game_state->>phase', 'eq', required)
        .select('id');
      if (updErr) return json({ error: updErr.message }, 500, cors);
      if (!updated || updated.length === 0) return json({ skipped: 'already advanced' }, 200, cors);

      // When the game ends, also flip the lobby lifecycle to finished.
      if (next.phase === 'GAME_OVER') {
        await admin.from('lobbies').update({ status: 'finished' }).eq('id', lobbyId);
      }
      return json({ resolved: next }, 200, cors);
    }

    // ── Branch 2: PLANNING → RESOLUTION turn resolution ────────────────────────
    if (remote.phase !== 'PLANNING') return json({ skipped: 'not planning' }, 200, cors);

    // Force is only valid once the (server-evaluated) turn deadline has passed.
    const deadlinePassed = !!remote.turnDeadlineUtc && Date.now() >= remote.turnDeadlineUtc;
    const outcome = resolveLobbyTurn(remote, force === true && deadlinePassed);
    if (!outcome) return json({ skipped: 'not all submitted' }, 200, cors);

    // Compare-and-set: only write if the row is STILL in PLANNING. A concurrent
    // duplicate invocation will match zero rows and no-op.
    const { data: updated, error: updErr } = await admin
      .from('lobbies')
      .update({ game_state: outcome.resolved, updated_at: new Date().toISOString() })
      .eq('id', lobbyId)
      .filter('game_state->>phase', 'eq', 'PLANNING')
      .select('id');
    if (updErr) return json({ error: updErr.message }, 500, cors);
    if (!updated || updated.length === 0) return json({ skipped: 'already resolved' }, 200, cors);

    return json({ resolved: outcome.resolved }, 200, cors);
  } catch (e) {
    return json({ error: String(e) }, 500, corsFor(req));
  }
});
