#!/bin/sh
# Prepare the generated Android Gradle project (src-tauri/gen/android) for a
# compliant, signed release build. `gen/` is gitignored and regenerated by
# `tauri android init`, so these fixes don't persist in the repo — run this ONCE
# after any `tauri android init` / gen regeneration (the build scripts also call
# it defensively). Idempotent; mirror of scripts/ios-prepare-gen.sh.
#
#   1. Sync launcher icons from source-of-truth (src-tauri/icons/android/) into
#      the generated res/ tree (adaptive icons + all densities).
#   2. Lock MainActivity to landscape (sensorLandscape) — parity with the iOS
#      UISupportedInterfaceOrientations policy.
#   3. Assert targetSdk >= 35 (Google Play requirement for new apps).
#   4. Wire release signing: copy ~/.android-keys/elector-upload.properties to
#      gen/android/keystore.properties and inject a null-safe signingConfig into
#      app/build.gradle.kts. Without the properties file, release builds are
#      simply unsigned (debug builds unaffected) — the script says so and
#      continues.
set -eu

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
gen="$repo_root/src-tauri/gen/android"
app_gradle="$gen/app/build.gradle.kts"
manifest="$gen/app/src/main/AndroidManifest.xml"
res="$gen/app/src/main/res"
keys_props="$HOME/.android-keys/elector-upload.properties"

if [ ! -f "$app_gradle" ] || [ ! -f "$manifest" ]; then
  echo "No generated Android project under src-tauri/gen/android — run 'npm run tauri:android:init' first." >&2
  exit 1
fi

# (1) launcher icons — the template ships Tauri-logo defaults; overwrite with ours.
if [ -d "$repo_root/src-tauri/icons/android" ]; then
  cp -R "$repo_root/src-tauri/icons/android/." "$res/"
  echo "Synced launcher icons into gen/android res/."
fi

# (2) landscape lock on MainActivity.
if grep -q 'android:screenOrientation=' "$manifest"; then
  echo "Manifest orientation lock already present."
else
  /usr/bin/sed -i '' 's/android:name="\.MainActivity"/android:name=".MainActivity" android:screenOrientation="sensorLandscape"/' "$manifest"
  grep -q 'android:screenOrientation="sensorLandscape"' "$manifest" || {
    echo "Failed to inject screenOrientation into $manifest — template drift, patch by hand." >&2
    exit 1
  }
  echo "Locked MainActivity to sensorLandscape."
fi

# (3) Play requires targetSdk >= 35 for new apps; the Tauri CLI template owns
#     this value, so fail loudly if a CLI upgrade ever regresses it.
target_sdk="$(grep -Eo 'targetSdk *= *[0-9]+' "$app_gradle" | grep -Eo '[0-9]+' | head -n1 || true)"
if [ -z "${target_sdk:-}" ] || [ "$target_sdk" -lt 35 ]; then
  echo "targetSdk is '${target_sdk:-unset}' in $app_gradle — Google Play requires >= 35." >&2
  exit 1
fi
echo "targetSdk $target_sdk OK."

# (4) release signing (marker-guarded so re-runs are no-ops).
if [ -f "$keys_props" ]; then
  cp "$keys_props" "$gen/keystore.properties"
  chmod 600 "$gen/keystore.properties"
  echo "Staged keystore.properties from $keys_props."
else
  echo "NOTE: $keys_props not found — release builds will be UNSIGNED."
  echo "      Create it with: password=..., keyAlias=upload, storeFile=$HOME/.android-keys/elector-upload.jks"
fi

if grep -q 'ELECTOR SIGNING' "$app_gradle"; then
  echo "Signing config already injected."
else
  # Loader before the android {} block…
  ruby - "$app_gradle" <<'RUBY'
path = ARGV.fetch(0)
gradle = File.read(path)

loader = <<~KTS
  // ELECTOR SIGNING BEGIN (injected by scripts/android-prepare-gen.sh)
  val keystorePropertiesFile = rootProject.file("keystore.properties")
  val keystoreProperties = Properties()
  if (keystorePropertiesFile.exists()) {
      keystorePropertiesFile.inputStream().use { keystoreProperties.load(it) }
  }
  // ELECTOR SIGNING END

  android {
KTS

signing = <<~KTS
      signingConfigs {
          if (keystorePropertiesFile.exists()) {
              create("release") {
                  keyAlias = keystoreProperties["keyAlias"] as String
                  keyPassword = keystoreProperties["password"] as String
                  storeFile = file(keystoreProperties["storeFile"] as String)
                  storePassword = keystoreProperties["password"] as String
              }
          }
      }
KTS

unless gradle.include?("android {")
  warn "Could not find the android {} block in #{path} — template drift."
  exit 1
end
gradle = gradle.sub("android {", loader.chomp)

# …signingConfigs at the top of the android block (right after the header we
# just rewrote), and a null-safe assignment in the release build type.
gradle = gradle.sub(/(\/\/ ELECTOR SIGNING END\n\nandroid \{\n)/) { "#{$1}#{signing}" }

unless gradle.include?('getByName("release")')
  warn "Could not find the release buildType in #{path} — template drift."
  exit 1
end
gradle = gradle.sub(/getByName\("release"\) \{\n/) {
  "#{$&}            signingConfig = signingConfigs.findByName(\"release\")\n"
}

# The template imports java.util.Properties in current CLIs; add if missing.
unless gradle.include?("import java.util.Properties")
  gradle = "import java.util.Properties\n" + gradle
end

File.write(path, gradle)
RUBY
  echo "Injected null-safe release signingConfig into app/build.gradle.kts."
fi

# (5) Firebase Cloud Messaging (push) for the elector-push plugin. Stage
#     google-services.json and wire the google-services Gradle plugin into the app
#     module — but ONLY when the config is available. Fail-soft: without it, FCM is
#     simply inactive (the elector-push Kotlin resolves an error, the client
#     no-ops) and normal Android builds are unaffected. The google-services plugin
#     REQUIRES the json at build time, so the two are wired together or not at all.
gs_src=""
for cand in "$HOME/.android-keys/google-services.json" "$repo_root/src-tauri/google-services.json"; do
  if [ -f "$cand" ]; then gs_src="$cand"; break; fi
done
if [ -n "$gs_src" ]; then
  cp "$gs_src" "$gen/app/google-services.json"
  echo "Staged google-services.json from $gs_src."
  if grep -q 'ELECTOR FCM' "$app_gradle"; then
    echo "google-services plugin already wired."
  else
    ruby - "$app_gradle" <<'RUBY'
path = ARGV.fetch(0)
g = File.read(path)

# Self-contained wiring (no root build.gradle edits): a buildscript classpath for
# the plugin, applied at the end of the module file. buildscript must precede the
# plugins {} block, so insert it after any leading import lines.
unless g.include?("com.google.gms:google-services")
  bs = <<~KTS
    // ELECTOR FCM BEGIN (injected by scripts/android-prepare-gen.sh)
    buildscript {
        repositories { google(); mavenCentral() }
        dependencies { classpath("com.google.gms:google-services:4.4.2") }
    }
    // ELECTOR FCM END
  KTS
  if g =~ /\A(?:import [^\n]*\n)+/
    g = g.sub(/\A((?:import [^\n]*\n)+)/) { "#{$1}\n#{bs}\n" }
  else
    g = bs + "\n" + g
  end
end

unless g.include?('apply(plugin = "com.google.gms.google-services")')
  g = g.rstrip + "\n\napply(plugin = \"com.google.gms.google-services\")\n"
end

File.write(path, g)
RUBY
    echo "Wired the google-services plugin into app/build.gradle.kts."
  fi
else
  echo "NOTE: google-services.json not found (checked ~/.android-keys and src-tauri/) —"
  echo "      Android push (FCM) stays inactive until it's added. Other builds unaffected."
fi

echo "Android gen preparation complete."
