#!/bin/sh
# Prepare the generated Android Gradle project (src-tauri/gen/android) for a
# compliant, signed release build. `gen/` is gitignored and regenerated by
# `tauri android init`, so these fixes don't persist in the repo — run this ONCE
# after any `tauri android init` / gen regeneration (the build scripts also call
# it defensively). Idempotent; mirror of scripts/ios-prepare-gen.sh.
#
#   1. Sync launcher icons from source-of-truth (src-tauri/icons/android/) into
#      the generated res/ tree (adaptive icons + all densities).
#   2. Lock MainActivity to landscape (sensorLandscape) — parity with the iOS
#      UISupportedInterfaceOrientations policy.
#   3. Assert targetSdk >= 35 (Google Play requirement for new apps).
#   4. Wire release signing: copy ~/.android-keys/elector-upload.properties to
#      gen/android/keystore.properties and inject a null-safe signingConfig into
#      app/build.gradle.kts. Without the properties file, release builds are
#      simply unsigned (debug builds unaffected) — the script says so and
#      continues.
set -eu

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
gen="$repo_root/src-tauri/gen/android"
app_gradle="$gen/app/build.gradle.kts"
manifest="$gen/app/src/main/AndroidManifest.xml"
res="$gen/app/src/main/res"
keys_props="$HOME/.android-keys/elector-upload.properties"

if [ ! -f "$app_gradle" ] || [ ! -f "$manifest" ]; then
  echo "No generated Android project under src-tauri/gen/android — run 'npm run tauri:android:init' first." >&2
  exit 1
fi

# (1) launcher icons — the template ships Tauri-logo defaults; overwrite with ours.
if [ -d "$repo_root/src-tauri/icons/android" ]; then
  cp -R "$repo_root/src-tauri/icons/android/." "$res/"
  echo "Synced launcher icons into gen/android res/."
fi

# (2) landscape lock on MainActivity.
if grep -q 'android:screenOrientation=' "$manifest"; then
  echo "Manifest orientation lock already present."
else
  /usr/bin/sed -i '' 's/android:name="\.MainActivity"/android:name=".MainActivity" android:screenOrientation="sensorLandscape"/' "$manifest"
  grep -q 'android:screenOrientation="sensorLandscape"' "$manifest" || {
    echo "Failed to inject screenOrientation into $manifest — template drift, patch by hand." >&2
    exit 1
  }
  echo "Locked MainActivity to sensorLandscape."
fi

# (3) Play requires targetSdk >= 35 for new apps; the Tauri CLI template owns
#     this value, so fail loudly if a CLI upgrade ever regresses it.
target_sdk="$(grep -Eo 'targetSdk *= *[0-9]+' "$app_gradle" | grep -Eo '[0-9]+' | head -n1 || true)"
if [ -z "${target_sdk:-}" ] || [ "$target_sdk" -lt 35 ]; then
  echo "targetSdk is '${target_sdk:-unset}' in $app_gradle — Google Play requires >= 35." >&2
  exit 1
fi
echo "targetSdk $target_sdk OK."

# (4) release signing (marker-guarded so re-runs are no-ops).
if [ -f "$keys_props" ]; then
  cp "$keys_props" "$gen/keystore.properties"
  chmod 600 "$gen/keystore.properties"
  echo "Staged keystore.properties from $keys_props."
else
  echo "NOTE: $keys_props not found — release builds will be UNSIGNED."
  echo "      Create it with: password=..., keyAlias=upload, storeFile=$HOME/.android-keys/elector-upload.jks"
fi

if grep -q 'ELECTOR SIGNING' "$app_gradle"; then
  echo "Signing config already injected."
else
  # Loader before the android {} block…
  ruby - "$app_gradle" <<'RUBY'
path = ARGV.fetch(0)
gradle = File.read(path)

loader = <<~KTS
  // ELECTOR SIGNING BEGIN (injected by scripts/android-prepare-gen.sh)
  val keystorePropertiesFile = rootProject.file("keystore.properties")
  val keystoreProperties = Properties()
  if (keystorePropertiesFile.exists()) {
      keystorePropertiesFile.inputStream().use { keystoreProperties.load(it) }
  }
  // ELECTOR SIGNING END

  android {
KTS

signing = <<~KTS
      signingConfigs {
          if (keystorePropertiesFile.exists()) {
              create("release") {
                  keyAlias = keystoreProperties["keyAlias"] as String
                  keyPassword = keystoreProperties["password"] as String
                  storeFile = file(keystoreProperties["storeFile"] as String)
                  storePassword = keystoreProperties["password"] as String
              }
          }
      }
KTS

unless gradle.include?("android {")
  warn "Could not find the android {} block in #{path} — template drift."
  exit 1
end
gradle = gradle.sub("android {", loader.chomp)

# …signingConfigs at the top of the android block (right after the header we
# just rewrote), and a null-safe assignment in the release build type.
gradle = gradle.sub(/(\/\/ ELECTOR SIGNING END\n\nandroid \{\n)/) { "#{$1}#{signing}" }

unless gradle.include?('getByName("release")')
  warn "Could not find the release buildType in #{path} — template drift."
  exit 1
end
gradle = gradle.sub(/getByName\("release"\) \{\n/) {
  "#{$&}            signingConfig = signingConfigs.findByName(\"release\")\n"
}

# The template imports java.util.Properties in current CLIs; add if missing.
unless gradle.include?("import java.util.Properties")
  gradle = "import java.util.Properties\n" + gradle
end

File.write(path, gradle)
RUBY
  echo "Injected null-safe release signingConfig into app/build.gradle.kts."
fi

echo "Android gen preparation complete."
