#!/bin/sh
# Prepare the generated iOS Xcode project (src-tauri/gen/apple) for a compliant,
# building archive. `gen/` is gitignored and regenerated by `tauri ios init`, so
# these fixes don't persist in the repo — run this ONCE after any `tauri ios init`
# / gen regeneration, before archiving. Idempotent.
#
#   1. Disable Xcode User Script Sandboxing — else the "Build Rust Code" phase
#      can't walk src-tauri to fingerprint the cargo build script and the archive
#      fails ("failed to determine package fingerprint" / "excludes stack").
#   2. Pin the iOS deployment target to 15 (Google Mobile Ads v12 + IAP plugin).
#   3. Stage the app privacy manifest (PrivacyInfo.xcprivacy) into the target
#      folder and add it to Copy Bundle Resources. Apple requires an app-level
#      privacy manifest; shipping AdMob without one => ITMS-91053.
set -eu

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
gen="$repo_root/src-tauri/gen/apple"
target_dir="$gen/election-sim_iOS"
target_info="$target_dir/Info.plist"
pbxproj="$(ls "$gen"/*.xcodeproj/project.pbxproj 2>/dev/null | head -n1 || true)"

if [ -z "${pbxproj:-}" ] || [ ! -f "$pbxproj" ]; then
  echo "No generated Xcode project under src-tauri/gen/apple — run 'tauri ios init' first." >&2
  exit 1
fi

# (1) + (2) + (4) build settings, applied directly to the pbxproj (works for both
#     `tauri ios build` and a direct Xcode archive).
/usr/bin/sed -i '' 's/ENABLE_USER_SCRIPT_SANDBOXING = YES;/ENABLE_USER_SCRIPT_SANDBOXING = NO;/g' "$pbxproj"
/usr/bin/sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 14\.0;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' "$pbxproj"
# (4) Clear the hardcoded "iPhone Developer" signing identity so Xcode's automatic
#     signing can choose Apple Development for device builds and Apple Distribution
#     for archive/App Store builds. Without this, xcodebuild archive ignores -allowProvisioningUpdates
#     and stays locked to the development certificate.
/usr/bin/sed -i '' 's/CODE_SIGN_IDENTITY = "iPhone Developer";/CODE_SIGN_IDENTITY = "";/g' "$pbxproj"
echo "Patched pbxproj: User Script Sandboxing off, iOS deployment target 15, signing identity cleared."

# Tauri's `bundle.iOS.infoPlist` merge has proven unreliable for the generated
# Xcode project, so copy the release-critical iOS app metadata directly into the
# plist Xcode archives. Keep this deterministic: every upload script run calls
# this preparation step before archiving.
if [ ! -f "$target_info" ]; then
  echo "Missing generated Info.plist at $target_info" >&2
  exit 1
fi

pb=/usr/libexec/PlistBuddy

$pb -c "Delete :CFBundleURLTypes" "$target_info" >/dev/null 2>&1 || true
$pb -c "Add :CFBundleURLTypes array" "$target_info"
$pb -c "Add :CFBundleURLTypes:0 dict" "$target_info"
$pb -c "Add :CFBundleURLTypes:0:CFBundleTypeRole string Editor" "$target_info"
$pb -c "Add :CFBundleURLTypes:0:CFBundleURLName string com.playelector.app" "$target_info"
$pb -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes array" "$target_info"
$pb -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes:0 string com.playelector.app" "$target_info"

plutil -replace UIRequiresFullScreen -bool YES "$target_info"
plutil -replace UIStatusBarStyle -string UIStatusBarStyleLightContent "$target_info"
plutil -replace UIViewControllerBasedStatusBarAppearance -bool NO "$target_info"

$pb -c "Delete :UISupportedInterfaceOrientations" "$target_info" >/dev/null 2>&1 || true
$pb -c "Add :UISupportedInterfaceOrientations array" "$target_info"
$pb -c "Add :UISupportedInterfaceOrientations:0 string UIInterfaceOrientationLandscapeLeft" "$target_info"
$pb -c "Add :UISupportedInterfaceOrientations:1 string UIInterfaceOrientationLandscapeRight" "$target_info"
$pb -c "Delete :UISupportedInterfaceOrientations~ipad" "$target_info" >/dev/null 2>&1 || true
$pb -c "Add :UISupportedInterfaceOrientations~ipad array" "$target_info"
$pb -c "Add :UISupportedInterfaceOrientations~ipad:0 string UIInterfaceOrientationLandscapeLeft" "$target_info"
$pb -c "Add :UISupportedInterfaceOrientations~ipad:1 string UIInterfaceOrientationLandscapeRight" "$target_info"

plutil -lint "$target_info" >/dev/null
plutil -extract CFBundleURLTypes.0.CFBundleURLSchemes.0 raw -o - "$target_info" | grep -qx "com.playelector.app"
plutil -extract UIRequiresFullScreen raw -o - "$target_info" | grep -qx "true"
echo "Patched generated Info.plist: OAuth URL scheme + fullscreen landscape policy."

# Sign in with Apple entitlement — the generated project already wires
# CODE_SIGN_ENTITLEMENTS to this (empty) file; the elector-siwa plugin's native
# sheet fails at runtime without the capability in the signed app. The App ID
# com.playelector.app has the capability enabled, so automatic signing picks up
# a matching provisioning profile.
entitlements="$target_dir/election-sim_iOS.entitlements"
if [ ! -f "$entitlements" ]; then
  echo "Missing generated entitlements file at $entitlements" >&2
  exit 1
fi
$pb -c "Delete :com.apple.developer.applesignin" "$entitlements" >/dev/null 2>&1 || true
$pb -c "Add :com.apple.developer.applesignin array" "$entitlements"
$pb -c "Add :com.apple.developer.applesignin:0 string Default" "$entitlements"
plutil -lint "$entitlements" >/dev/null
plutil -extract "com\\.apple\\.developer\\.applesignin.0" raw -o - "$entitlements" | grep -qx "Default"
echo "Patched entitlements: Sign in with Apple (Default)."

# Push Notifications entitlement (aps-environment) for the elector-push plugin's
# APNs registration. Defaults to 'development'; ios-upload.sh exports
# APS_ENVIRONMENT=production for the App Store archive so it ships prod device
# tokens (matching the elector-push Swift #if DEBUG environment: debug=sandbox,
# release=prod). The App ID com.playelector.app must have Push Notifications
# enabled so automatic signing finds a matching provisioning profile. (Only alert
# pushes are sent, so no UIBackgroundModes/remote-notification is needed.)
aps_env="${APS_ENVIRONMENT:-development}"
$pb -c "Delete :aps-environment" "$entitlements" >/dev/null 2>&1 || true
$pb -c "Add :aps-environment string $aps_env" "$entitlements"
plutil -lint "$entitlements" >/dev/null
plutil -extract "aps-environment" raw -o - "$entitlements" | grep -qx "$aps_env"
echo "Patched entitlements: Push Notifications (aps-environment=$aps_env)."

# (3) stage the privacy manifest next to the app target.
cp "$repo_root/src-tauri/PrivacyInfo.xcprivacy" "$target_dir/PrivacyInfo.xcprivacy"
if grep -q "PrivacyInfo.xcprivacy" "$pbxproj"; then
  echo "PrivacyInfo.xcprivacy already referenced by the Xcode project."
else
  ruby - "$pbxproj" <<'RUBY'
path = ARGV.fetch(0)
project = File.read(path)
file_ref = "C0DEC0DEC0DEC0DEC0DEC002"
build_file = "C0DEC0DEC0DEC0DEC0DEC003"

replacements = {
  "/* End PBXBuildFile section */" =>
    "\t\t#{build_file} /* PrivacyInfo.xcprivacy in Resources */ = {isa = PBXBuildFile; fileRef = #{file_ref} /* PrivacyInfo.xcprivacy */; };\n/* End PBXBuildFile section */",
  "/* End PBXFileReference section */" =>
    "\t\t#{file_ref} /* PrivacyInfo.xcprivacy */ = {isa = PBXFileReference; lastKnownFileType = text.xml; path = PrivacyInfo.xcprivacy; sourceTree = \"<group>\"; };\n/* End PBXFileReference section */",
  "\t\t\t\t4FD9985376A9A16BE2ACBE84 /* Info.plist */,\n" =>
    "\t\t\t\t#{file_ref} /* PrivacyInfo.xcprivacy */,\n\t\t\t\t4FD9985376A9A16BE2ACBE84 /* Info.plist */,\n",
  "\t\t\t\tE9812718B0143A0FEBEA3F03 /* Assets.xcassets in Resources */,\n" =>
    "\t\t\t\t#{build_file} /* PrivacyInfo.xcprivacy in Resources */,\n\t\t\t\tE9812718B0143A0FEBEA3F03 /* Assets.xcassets in Resources */,\n"
}

replacements.each do |needle, replacement|
  unless project.include?(needle)
    warn "Could not find expected pbxproj marker while adding PrivacyInfo.xcprivacy: #{needle.inspect}"
    exit 1
  end
  project = project.sub(needle, replacement)
end

File.write(path, project)
RUBY
  echo "Staged PrivacyInfo.xcprivacy and added it to Copy Bundle Resources."
fi
