#!/bin/sh
# Prepare the generated iOS Xcode project (src-tauri/gen/apple) for a compliant,
# building archive. `gen/` is gitignored and regenerated by `tauri ios init`, so
# these fixes don't persist in the repo — run this ONCE after any `tauri ios init`
# / gen regeneration, before archiving. Idempotent.
#
#   1. Disable Xcode User Script Sandboxing — else the "Build Rust Code" phase
#      can't walk src-tauri to fingerprint the cargo build script and the archive
#      fails ("failed to determine package fingerprint" / "excludes stack").
#   2. Pin the iOS deployment target to 15 (Google Mobile Ads v12 + IAP plugin).
#   3. Stage the app privacy manifest (PrivacyInfo.xcprivacy) into the target
#      folder — Apple requires an app-level privacy manifest; shipping AdMob
#      without one => ITMS-91053. See the note below to finish wiring it.
set -eu

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
gen="$repo_root/src-tauri/gen/apple"
target_dir="$gen/election-sim_iOS"
pbxproj="$(ls "$gen"/*.xcodeproj/project.pbxproj 2>/dev/null | head -n1 || true)"

if [ -z "${pbxproj:-}" ] || [ ! -f "$pbxproj" ]; then
  echo "No generated Xcode project under src-tauri/gen/apple — run 'tauri ios init' first." >&2
  exit 1
fi

# (1) + (2) + (4) build settings, applied directly to the pbxproj (works for both
#     `tauri ios build` and a direct Xcode archive).
/usr/bin/sed -i '' 's/ENABLE_USER_SCRIPT_SANDBOXING = YES;/ENABLE_USER_SCRIPT_SANDBOXING = NO;/g' "$pbxproj"
/usr/bin/sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 14\.0;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' "$pbxproj"
# (4) Clear the hardcoded "iPhone Developer" signing identity so Xcode's automatic
#     signing can choose Apple Development for device builds and Apple Distribution
#     for archive/App Store builds. Without this, xcodebuild archive ignores -allowProvisioningUpdates
#     and stays locked to the development certificate.
/usr/bin/sed -i '' 's/CODE_SIGN_IDENTITY = "iPhone Developer";/CODE_SIGN_IDENTITY = "";/g' "$pbxproj"
echo "Patched pbxproj: User Script Sandboxing off, iOS deployment target 15, signing identity cleared."

# (3) stage the privacy manifest next to the app target.
cp "$repo_root/src-tauri/PrivacyInfo.xcprivacy" "$target_dir/PrivacyInfo.xcprivacy"
if grep -q "PrivacyInfo.xcprivacy" "$pbxproj"; then
  echo "PrivacyInfo.xcprivacy already referenced by the Xcode project."
else
  echo "Staged PrivacyInfo.xcprivacy in $target_dir."
  echo "ONE-TIME: in Xcode, drag election-sim_iOS/PrivacyInfo.xcprivacy into the app target's"
  echo "          'Copy Bundle Resources' build phase (it then persists in the pbxproj)."
fi
