#!/bin/sh
# Disable Xcode "User Script Sandboxing" in the generated iOS Xcode project.
#
# Tauri's src-tauri/gen/ is gitignored and regenerated by `tauri ios init`.
# The generated project sets ENABLE_USER_SCRIPT_SANDBOXING = YES, which sandboxes
# the "Build Rust Code" build phase. cargo must walk src-tauri (reading .gitignore
# excludes) to fingerprint the build script, and the sandbox denies that directory
# listing, so the archive fails with:
#   error: failed to determine package fingerprint for build script for election-sim
#   Caused by: failed to determine the most recently modified file in .../src-tauri
#   Caused by: Failed to update the excludes stack to see if a path is excluded
#
# Run this once after `tauri ios init` (or any gen/apple regeneration), before
# archiving in Xcode. Idempotent.
set -eu

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
pbxproj="$(ls "$repo_root"/src-tauri/gen/apple/*.xcodeproj/project.pbxproj 2>/dev/null | head -n1 || true)"

if [ -z "${pbxproj:-}" ] || [ ! -f "$pbxproj" ]; then
  echo "No generated Xcode project found under src-tauri/gen/apple — run 'tauri ios init' first." >&2
  exit 1
fi

if grep -q "ENABLE_USER_SCRIPT_SANDBOXING = YES;" "$pbxproj"; then
  /usr/bin/sed -i '' 's/ENABLE_USER_SCRIPT_SANDBOXING = YES;/ENABLE_USER_SCRIPT_SANDBOXING = NO;/g' "$pbxproj"
  echo "Disabled User Script Sandboxing in $pbxproj"
else
  echo "User Script Sandboxing already disabled (or setting absent) in $pbxproj"
fi
